######################################################
networks:
  vpnmedia-network:
    name: vpnmedia-network
    driver: bridge
    external: true
######################################################
secrets:
  openvpn_password:
    file: ${CONFIGS}/gluetun/proton_pwd.txt
  openvpn_user:
    file: ${CONFIGS}/gluetun/proton_user.txt
######################################################

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8050:8000
      - ${WEBUI_PORT_BAZARR}:6767 # WebUI Portal: Bazarr
      - ${WEBUI_PORT_PROWLARR}:9696 # WebUI Portal: Prowlarr
      - ${WEBUI_PORT_RADARR}:7878 # WebUI Portal: Radarr
      - ${WEBUI_PORT_SONARR}:8989 # WebUI Portal: Sonarr
      - ${WEBUI_PORT_QBITTORRENT}:${WEBUI_PORT_QBITTORRENT} # WebUI Portal: qBittorrent
      - ${FLARESOLVERR_PORT}:8191 # Service Port: FlareSolverr
    volumes:
      - ${CONFIGS}/gluetun:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      SERVER_REGIONS: US California
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      SHADOWSOCKS: on
    networks:
      - vpnmedia-network
    secrets:
      - openvpn_password
      - openvpn_user 

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${CONFIGS}/qbittorrent:/config
      - ${MEDIA}/downloads:/data/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=${WEBUI_PORT_QBITTORRENT}
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod
    network_mode: service:gluetun

