networks:
  vpnmedia-network:
    name: vpnmedia-network
    driver: bridge
    external: true
secrets:
  openvpn_password:
    file: ${CONFIGS}/gluetun/proton_pwd.txt
  openvpn_user:
    file: ${CONFIGS}/gluetun/proton_user.txt

services:

  # VPN and Network manager
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8050:8000
      - ${WEBUI_PORT_BAZARR}:6767 # WebUI Portal: Bazarr
      - ${WEBUI_PORT_PROWLARR}:9696 # WebUI Portal: Prowlarr
      - ${WEBUI_PORT_RADARR}:7878 # WebUI Portal: Radarr
      - ${WEBUI_PORT_SONARR}:8989 # WebUI Portal: Sonarr
      - ${WEBUI_PORT_QBITTORRENT}:${WEBUI_PORT_QBITTORRENT} # WebUI Portal: qBittorrent
      - ${FLARESOLVERR_PORT}:8191 # Service Port: FlareSolverr
    volumes:
      - ${CONFIGS}/gluetun:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: openvpn
      SERVER_COUNTRIES: United States
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      SHADOWSOCKS: on
    networks:
      - vpnmedia-network
    secrets:
      - openvpn_password
      - openvpn_user 

# Torrent manager
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    user: ${PUID}:${PGID}
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${CONFIGS}/qbittorrent:/config
      - ${DATA}/downloads:/data/downloads
    environment:
      TZ: ${TIMEZONE}
      WEBUI_PORT: ${WEBUI_PORT_QBITTORRENT}
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod
    network_mode: service:gluetun

  # subtitles for radarr and sonarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${CONFIGS}/bazarr:/config
      - ${DATA}/media:/data/media
    environment:
      DOCKER_MODS: ghcr.io/gilbn/theme.park:bazarr
      #- TP_THEME=${TP_THEME}
    network_mode: service:gluetun

  # cloudflare proxy server
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
      TZ: ${TIMEZONE}
    network_mode: service:gluetun

  # indexer and search manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${CONFIGS}/prowlarr:/config
    environment:
      TZ: ${TIMEZONE}
      DOCKER_MODS: ghcr.io/gilbn/theme.park:prowlarr
      #- TP_THEME=${TP_THEME}
    network_mode: service:gluetun

  # movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${CONFIGS}/radarr:/config
      - ${DATA}:/data
    environment:
      TZ: ${TIMEZONE}
      DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
      #- TP_THEME=${TP_THEME}
    network_mode: service:gluetun

  # tv shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${CONFIGS}/sonarr:/config
      - ${DATA}:/data
    environment:
      TZ: ${TIMEZONE}
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
      #- TP_THEME=${TP_THEME}
    network_mode: service:gluetun

  # profile manager
  profilarr:
    image: santiagosayshey/profilarr:beta
    container_name: profilarr
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    ports:
        - 6868:6868
    volumes:
        - ${CONFIGS}/profilarr:/config
    environment:
      TZ: America/Los_Angeles

  # unzips any downloaded archives
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - ${DATA}/downloads/:/downloads
      - ${CONFIGS}/unpackerr/unpackerr.conf:/config/unpackerr.conf:ro
